# Generated by Django 5.2.7 on 2025-10-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_alter_article_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.tour', verbose_name='Тур'),
        ),
    ]
