# Generated by Django 5.2.7 on 2025-10-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_alter_article_tour_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Additional_services_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp2.additional_service', verbose_name='Дополнительные услуги'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_participants',
            field=models.IntegerField(default=0, verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.user', verbose_name='Пользовватель'),
        ),
    ]
