# Generated by Django 5.2.7 on 2025-10-17 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_alter_booking_additional_services_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.user', verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='map',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='map',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='user',
            name='booking_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp2.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='user',
            name='map_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp2.map', verbose_name='Карта'),
        ),
    ]
