# Generated by Django 5.2.7 on 2025-10-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0007_alter_article_tour_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
